### ISSUE TITLE
Minecraft startup crash with UniDict and WanionLib

### ISSUE THREAD

**Issue by MustHaveToTry** [WanionCane/UniDict#205]
When I start minecraft with any version of Unidict and Wanionlib my game crashes, the crash log shows that the error is due to UniDict, I can't figure out what's wron
[crash-2021-11-28_15.49.48-client.txt](https://github.com/WanionCane/UniDict/files/7613574/crash-2021-11-28_15.49.48-client.txt)

Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniDict (unidict)
Caused by: java.lang.NoClassDefFoundError: reborncore/api/praescriptum/recipes/Recipe
    at wanion.unidict.integration.TechRebornIntegration.<init>(TechRebornIntegration.java:28)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at wanion.unidict.integration.IntegrationModule$$Lambda$2201/634433811.instantiate(Unknown Source)
    at wanion.lib.module.AbstractModule$Manager.lambda$getInstances$0(AbstractModule.java:112)
    at wanion.lib.module.AbstractModule$Manager$$Lambda$4408/1044403047.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at wanion.lib.module.AbstractModule$Manager.getInstances(AbstractModule.java:110)
    at wanion.lib.module.AbstractModule.start(AbstractModule.java:41)
    at wanion.lib.module.ModuleHandler.lambda$startModules$0(ModuleHandler.java:39)
    at wanion.lib.module.ModuleHandler$$Lambda$2206/1335427656.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at wanion.lib.module.ModuleHandler.startModules(ModuleHandler.java:31)
    at wanion.unidict.proxy.CommonProxy.postInit(CommonProxy.java:67)
    at wanion.unidict.proxy.ClientProxy.postInit(ClientProxy.java:19)
    at wanion.unidict.UniDict.postInit(UniDict.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: reborncore.api.praescriptum.recipes.Recipe
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 59 more
Caused by: java.lang.NullPointerException

**Comment by WanionCane** [comment]
Hello, a temporary fix for now, disable TechReborn integration in config/unidict/IntegrationModule.cfg

`B:TechReborn=false`

**Comment by ElektroKill** [comment]
Hi, it seems TechReborn have updated the recipe system code. The solution proposed above will disable the integration and thus stop the crash. However, the recipes won't be unified. I will see what can be done to resolve this properly later. :)
