### ISSUE TITLE
[1.11.2] NoClassDefFoundError: cofh/thermalexpansion/util/managers/machine/CompactorManager$RecipeCompactor

### ISSUE THREAD

**Issue by wjrogers** [WanionCane/UniDict#31]
Forge 2393
Thermal Expansion 5.2.5.18
UniDict 1.1
```
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/util/managers/machine/CompactorManager$RecipeCompactor
	at wanion.unidict.integration.TEIntegration.fixCompactorRecipes(TEIntegration.java:55)
	at wanion.unidict.integration.TEIntegration.call(TEIntegration.java:36)
	at wanion.unidict.integration.TEIntegration.call(TEIntegration.java:25)
```
[latest.txt](https://github.com/WanionCane/UniDict/files/1130029/latest.txt)

**Comment by WanionCane** [comment]
Fixed on [UniDict-1.11.2-1.1b.jar](https://minecraft.curseforge.com/projects/unidict/files/2448632)
