### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by GreyMamoN** [WanionCane/UniDict#70]
Forge **14.23.1.2587**
Installed mods:
Craft Tweaker 2 **1.12-4.0.12**
Uni Dict **1.12.2-2.1**
Wanion Lib **1.12.2-1.4**

If installed Uni Dict **1.12.2-2.0** starts without errors

`
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: java.lang.RuntimeException: Expansion method remove must be static
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at stanhebben.zenscript.TypeExpansion.checkStatic(TypeExpansion.java:457)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at stanhebben.zenscript.TypeExpansion.expand(TypeExpansion.java:134)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at crafttweaker.zenscript.GlobalRegistry.registerExpansion(GlobalRegistry.java:60)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at crafttweaker.CraftTweakerAPI.registerClass(CraftTweakerAPI.java:205)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at wanion.unidict.plugin.crafttweaker.UniDictCraftTweakerPlugin.registerAbstractRemovalByKind(UniDictCraftTweakerPlugin.java:75)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at wanion.unidict.plugin.crafttweaker.UniDictCraftTweakerPlugin.preInit(UniDictCraftTweakerPlugin.java:69)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at wanion.unidict.proxy.CommonProxy.preInit(CommonProxy.java:46)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at wanion.unidict.UniDict.preInit(UniDict.java:84)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[23:55:10] [Server thread/INFO] [STDERR]: [crafttweaker.zenscript.GlobalRegistry:registerExpansion:64]: 	at java.lang.Thread.run(Thread.java:748)

`

**Comment by WanionCane** [comment]
weird, are u using the new UniDict CT commands? if yes, could you please share the script with me?

**Comment by GreyMamoN** [comment]
The folder with the scripts is empty, only the described mods are installed

p.s. Sorry for bad English

**Comment by WanionCane** [comment]
oh okay, I found the problem, it will be fixed on the next version, thanks XD
sorry for my english too lol
